version: '2'

services:
  rabbitmq:
    image: rabbitmq:management
    mem_limit: 512m
    mem_reservation: 256M
    ports:
      - "5672:5672"
      - "15672:15672"

  postgre:
    image: 'postgres'
    container_name: postgre
    mem_limit: 512m
    mem_reservation: 256M
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass

  producer:
    image: mikhailmarch/rabbit-producer:latest
    mem_limit: 512m
    mem_reservation: 256M
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq

  consumer:
    image: mikhailmarch/rabbit-consumer:latest
    mem_limit: 512m
    mem_reservation: 256M
    build:
      context: .
    container_name: consumer
    depends_on:
      - postgre
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgre:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres_pass
      - RABBIT_HOST=rabbitmq