kind: Service
apiVersion: v1
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  ports:
    - nodePort: 30163
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: listener
  type: NodePort